---
- name: Copy MetricBeat package
  copy:
    src: files/deb/metricbeat-6.2.2-amd64.deb
    dest: /tmp

- name: Install MetricBeat package
  apt:
    deb: /tmp/metricbeat-6.2.2-amd64.deb
#    deb: https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-6.2.2-amd64.deb

- name: Backing up MetricBeat config
  command: cp -n /etc/metricbeat/metricbeat.yml /etc/metricbeat/metricbeat.yml.orig

- name: Installing MetricBeat config
  template:
    src: "templates/common/metricbeat.yml.j2"
    dest: /etc/metricbeat/metricbeat.yml

- name: Enable MetricBeat
  systemd:
    enabled: yes
    name: metricbeat
